######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 20 00:39:45 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
