# The top level Makefile

all:	
	cd myProg 	&& $(MAKE)
	#cd JustForFun 	&& $(MAKE)
	#cd basics	&& $(MAKE)
	#cd forms	&& $(MAKE)
	#cd menus	&& $(MAKE)
	#cd panels	&& $(MAKE)
	@echo 
	@echo "*********************************************"
	@echo "All files Built"
	@echo "Please move to demo/exe directory"
	@echo "Execute each file to see examples in action"
	@echo "*********************************************"
	@echo
clean:
	cd myProg 	&& $(MAKE) clean
	#cd JustForFun 	&& $(MAKE) clean
	#cd basics	&& $(MAKE) clean
	#cd forms	&& $(MAKE) clean
	#cd menus	&& $(MAKE) clean
	#cd panels	&& $(MAKE) clean
