######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 20 23:49:06 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ageInput.cpp
