######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 20 19:17:41 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
