######################################################################
# Automatically generated by qmake (2.01a) Mon May 29 20:16:34 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
