CC=g++ -lgmp -Wall -pedantic -g 
MERSENNE: 
	$(CC) mersenne_bigint_lucas.cpp -o mersenne_lucas.o
	$(CC) mersenne_bigint_bruteforce.cpp -o mersenne_bruteforce.o
	$(CC) prime_bigint_bruteforce.cpp -o prime_bruteforce.o
