######################################################################
# Automatically generated by qmake (2.01a) Mon May 29 19:37:49 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
