




/*
     FILE ARCHIVED ON 1:36:23 Mar 28, 2011 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 17:12:44 Apr 9, 2017.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
function initPubTailorConfig(){


}

