######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 21 00:56:40 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
