print("What is your name?")
name = input()
print("What is your address?")
address = input()
print("What is your phone number?")
number = input()
print("What is your major?")
major = input()
print("Your name: ", name)
print("Your address: ", address)
print("Your number: ", number)
print("Your major: ", major)